[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true
  headers = {Content-Type = "application/xml"}

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true
  headers = {Content-Type = "text/plain"}

[[redirects]]
  from = "/kvk-basvuru-formu"
  to = "/kvk-basvuru-formu.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/en/kvk-application-form"
  to = "/kvk-basvuru-formu.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/kvk-aydinlatma-metni"
  to = "/kvk-aydinlatma-metni.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/en/kvk-clarification-form"
  to = "/kvk-aydinlatma-metni.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200